services:      
  db:
    container_name: db_postgres_5432
    build: ./db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
    ports:
      - "8085:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - shared-data:/shared
    restart: unless-stopped
    networks:
      - network

  account:
    container_name: account-service
    build: ./account
    ports:
      - "8081:8081"  
    volumes:
      - shared-data:/shared
    restart: unless-stopped
    networks:
      - network
    depends_on:
      - db
      - elasticsearch

  hospital:
    container_name: hospital-service
    build: ./hospital
    ports:
      - "8082:8081"
    volumes:
      - shared-data:/shared
    restart: unless-stopped
    networks:
      - network
    depends_on:
      - db
      - account

  timetable:
    container_name: timetable-service
    build: ./timetable
    ports:
      - "8083:8081"
    volumes:
      - shared-data:/shared
    restart: unless-stopped
    networks:
      - network
    depends_on:
      - db
      - account

  history:
    container_name: history-service
    build: ./history
    ports:
      - "8084:8081"
    volumes:
      - shared-data:/shared
    restart: unless-stopped
    networks:
      - network
    depends_on:
      - db
      - account

  elasticsearch:
    image: elasticsearch:7.17.25
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - network.host=0.0.0.0
    restart: unless-stopped
    ports:
      - "8086:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - network

  kibana:
    image: kibana:7.17.25
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    restart: unless-stopped
    ports:
      - "8087:5601"
    networks:
      - network
    depends_on:
      - elasticsearch
  

volumes:
  postgres-data:
  shared-data:
  esdata:

networks:
  network:
    driver: bridge
