version: '3.8'

services:      
  db:
    container_name: db_postgres
    build: ./db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
    ports:
      - "8085:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - shared-data:/shared
    restart: always
    networks:
      - network

  account:
    container_name: account-service
    build: ./account
    ports:
      - "8081:8081"  
    volumes:
      - shared-data:/shared
    restart: always
    networks:
      - network

  hospital:
    container_name: hospital-service
    build: ./hospital
    ports:
      - "8082:8081"
    volumes:
      - shared-data:/shared
    restart: always
    networks:
      - network

  timetable:
    container_name: timetable-service
    build: ./timetable
    ports:
      - "8083:8081"
    volumes:
      - shared-data:/shared
    restart: always
    networks:
      - network

  history:
    container_name: history-service
    build: ./history
    ports:
      - "8084:8081"
    volumes:
      - shared-data:/shared
    restart: always
    networks:
      - network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTIC_PASSWORD=password
    ports:
      - "8086:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=password
    ports:
      - "8087:5601"
    networks:
      - elastic
  

volumes:
  postgres-data:
  shared-data:
  esdata:

networks:
  network:
    driver: bridge
  elastic:
    driver: bridge
