version: '3.8'

services:
  db:
    container_name: db_postgres
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
    ports:
      - "8085:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - shared-data:/shared
    restart: always
    networks:
      - network

  account:
    container_name: account-service
    build: ./account
    ports:
      - "8081:8081"  
    volumes:
      - shared-data:/shared
    restart: always
    networks:
      - network

  hospital:
    container_name: hospital-service
    build: ./hospital
    ports:
      - "8082:8081"
    volumes:
      - shared-data:/shared
    restart: always
    networks:
      - network

volumes:
  postgres-data:
  shared-data:

networks:
  network:
    driver: bridge
